# Before Getting Started

In [1]:
# Dependencies
import pandas as pd
import folium

In [2]:
# Mapping test of one park (e.g. Grand Canyon of the yellowstone: 61.4182147,-142.6028439)
folium_map = folium.Map(location=[61.4182147,-142.6028439])
marker = folium.Marker([61.4182147,-142.6028439], 
         popup='Grand Canyon of the Yellowstone').add_to(folium_map)

# Display map
folium_map

# Processing National Parks Data

## Pre-Processing Data

### 1. To get started, create a DataFrame containing parameters and the location of each national park

In [3]:
# Load data collected from national park information.
parks_data = pd.read_csv("top10parks_by_Winter.csv")

# Display the DataFrame generated from loaded data
parks_data.head()

,Park,Date of Review,Rating,Total Number of Reviews,Aggregate,"State,USA only",Country,Age,Gender (M or F),Relationship (Couple or Single),Occupation,Top Activity,Season
0,"Arches National Park, Utah","Dec 10,2017",2,36,4.9,Georgia,USA,11,M,Married,494776,Delicate Arch Visit,winter
1,"Arches National Park, Utah","Feb 26,2017",2,36,4.9,Tennesse,USA,6,M,Married,457545,Delicate Arch Visit,winter
2,"Arches National Park, Utah","Ja 23,2017",2,36,4.9,Virginia,USA,29,F,Married,132621,Delicate Arch Visit,winter
3,"Arches National Park, Utah","Dec 3,2017",2,15,4.9,New York,USA,63,M,Single,138321,Delicate Arch Visit,winter
4,"Arches National Park, Utah","Jan 23,2017",2,15,4.9,Idaho,USA,38,M,Single,467195,Delicate Arch Visit,winter

In [4]:
# Load coordinate data of each national park.
parks_coord = pd.read_csv("parks_coord.csv")

# Display the DataFrame generated from loaded data
parks_coord.head()

                                      Park  Latitude  Longitude
0               Arches National Park, Utah   38.7331    -109.59
1  Mount Rainier National Park, Washington   46.8800    -121.73
2         Bryce Canyon National Park, Utah   37.5930    -112.19
3       Yosemite National Park, California   37.8651    -119.54
4             Denali National Park, Alaska   63.1148    -151.19

In [5]:
# Merging data
parks_df = pd.merge(parks_data, parks_coord, on='Park')

# Display the DataFrame generated from merged data
parks_df

,Park,Date of Review,Rating,Total Number of Reviews,Aggregate,"State,USA only",Country,Age,Gender (M or F),Relationship (Couple or Single),Occupation,Top Activity,Season,Latitude,Longitude
0,"Arches National Park, Utah","Dec 10,2017",2,36,4.90,Georgia,USA,11,M,Married,494776,Delicate Arch Visit,winter,38.7331,-109.59
1,"Arches National Park, Utah","Feb 26,2017",2,36,4.90,Tennesse,USA,6,M,Married,457545,Delicate Arch Visit,winter,38.7331,-109.59
2,"Arches National Park, Utah","Ja 23,2017",2,36,4.90,Virginia,USA,29,F,Married,132621,Delicate Arch Visit,winter,38.7331,-109.59
3,"Arches National Park, Utah","Dec 3,2017",2,15,4.90,New York,USA,63,M,Single,138321,Delicate Arch Visit,winter,38.7331,-109.59
4,"Arches National Park, Utah","Jan 23,2017",2,15,4.90,Idaho,USA,38,M,Single,467195,Delicate Arch Visit,winter,38.7331,-109.59
5,"Bryce Canyon National Park, Utah","Dec 26,2017",5,153,4.90,New jersey,USA,30,F,Married,203736,Bryce Canyon National Park,winter,37.5930,-112.19
6,"Bryce Canyon National Park, Utah","Dec 26,2017",5,153,4.90,Texas,USA,30,M,Married,275290,Bryce Canyon National Park,winter,37.5930,-112.19
7,"Bryce Canyon National Park, Utah","Dec 17,2017",5,153,4.90,Missouri,USA,45,F,Married,452638,Bryce Canyon National Park,winter,37.5930,-112.19
8,"Bryce Canyon National Park, Utah","Dec 23,2017",5,21,4.90,pennsylvenia,USA,58,M,Single,178474,Bryce Canyon National Park,winter,37.5930,-112.19
9,"Bryce Canyon National Park, Utah","Feb 15,2017",5,21,4.90,Florida,USA,12,F,Single,430654,Bryce Canyon National Park,winter,37.5930,-112.19
10,"Yosemite National Park, California","Dec 17,2017",2,66,4.90,California,USA,59,M,Married,274108,Glacier Point,winter,37.8651,-119.54
11,"Yosemite National Park, California","Feb 15,2017",2,66,4.90,Michigan,USA,81,M,Married,87165,Glacier Point,winter,37.8651,-119.54
12,"Yosemite National Park, California","Jan 14,2017",2,66,4.90,California,USA,44,M,Married,237117,Glacier Point,winter,37.8651,-119.54
13,"Yosemite National Park, California","jan 11,2017",2,14,4.90,Utah,USA,63,F,Single,107574,Glacier Point,winter,37.8651,-119.54
14,"Yosemite National Park, California","Jan 4,2017",2,14,4.90,oregon,USA,9,F,Single,215582,Glacier Point,winter,37.8651,-119.54
15,"Denali National Park, Alaska","Dec 31,2017",5,27,4.90,Tennesse,USA,71,M,Married,57914,Denali,winter,63.1148,-151.19
16,"Denali National Park, Alaska","Dec 16,2017",5,27,4.90,Minnesota,USA,10,M,Married,480712,Denali,winter,63.1148,-151.19
17,"Denali National Park, Alaska","Feb 13,2017",5,27,4.90,North Carolina,USA,21,F,Married,407586,Denali,winter,63.1148,-151.19
18,"Denali National Park, Alaska","Jan 21,2017",5,27,4.90,Michigan,USA,5,F,Married,148228,Denali,winter,63.1148,-151.19
19,"Denali National Park, Alaska","Jan 7,2017",5,27,4.90,Texas,USA,64,M,Married,421048,Denali,winter,63.1148,-151.19
20,"Grand Canyon National Park, Arizona","Dec 30,2017",5,833,4.90,Texas,USA,43,M,Married,289272,Grand Canyon South Rim,winter,36.1070,-112.11
21,"Grand Canyon National Park, Arizona","Dec 27,2017",5,833,4.90,Illinois,USA,22,M,Married,185618,Grand Canyon South Rim,winter,36.1070,-112.11
22,"Grand Canyon National Park, Arizona","Dec 26,2017",5,833,4.90,Florida,USA,69,F,Married,232514,Grand Canyon South Rim,winter,36.1070,-112.11
23,"Grand Canyon National Park, Arizona","Dec 10,2017",5,96,4.90,Florida,USA,15,F,Single,347434,Grand Canyon South Rim,winter,36.1070,-112.11
24,"Grand Canyon National Park, Arizona","Dec 4,2017",5,96,4.90,Utah,USA,27,M,Single,323765,Grand Canyon South Rim,winter,36.1070,-112.11
25,"Yellowstone National Park, Wyoming","Dec 18,2017",2,15,4.90,New York,USA,38,M,Married,103907,Grand Canyon of the yellowstone,winter,44.4280,-110.59
26,"Yellowstone National Park, Wyoming","Feb 15,2017",2,86,4.90,Oregon,USA,34,F,Married,184566,Grand Canyon of the yellowstone,winter,44.4280,-110.59
27,"Yellowstone National Park, Wyoming","Jan 26,2017",2,16,4.90,california,USA,28,M,Married,477975,Grand Canyon of the yellowstone,winter,44.4280,-110.59
28,"Yellowstone National Park, Wyoming","Feb 23,2017",2,9,4.90,Idaho,USA,93,M,Single,306312,Grand Canyon of the yellowstone,winter,44.4280,-110.59
29,"Yellowstone National Park, Wyoming","Feb 15,2017",2,86,4.90,New York,USA,97,F,Married,206876,Grand Canyon of the yellowstone,winter,44.4280,-110.59
30,"Rocky Mountain National Park, Colorado","Dec 17,2017",5,34,4.90,Michigan,USA,30,F,Married,399116,Trail Ridge Road,winter,40.3428,-105.68
31,"Rocky Mountain National Park, Colorado","Feb 13,2017",5,34,4.90,Minnesota,USA,28,F,Married,113495,Trail Ridge Road,winter,40.3428,-105.68
32,"Rocky Mountain National Park, Colorado","Jan 4,2017",5,34,4.90,Florida,USA,1,F,Married,399445,Trail Ridge Road,winter,40.3428,-105.68
33,"Rocky Mountain National Park, Colorado","Feb 14,2017",5,5,4.90,Colorado,USA,26,M,Single,179744,Trail Ridge Road,winter,40.3428,-105.68
34,"Rocky Mountain National Park, Colorado","Jan 1,2017",5,34,4.90,california,USA,66,F,Married,297285,Trail Ridge Road,winter,40.3428,-105.68
35,"Lassen Volcanic National Park, California","Feb 20,2017",5,5,4.90,ohio,USA,57,M,Single,469391,Mount Lassen,winter,40.4977,-121.42
36,"Lassen Volcanic National Park, California","Dec 24,20155",5,5,4.99,California,USA,25,F,Single,145027,Mount Lassen,winter,40.4977,-121.42
37,"Lassen Volcanic National Park, California","Dec 24,2014",5,5,4.99,California,USA,7,F,Single,274779,Mount Lassen,winter,40.4977,-121.42
38,"Lassen Volcanic National Park, California","Feb 22,2014",3,5,2.99,Texas,USA,3,M,Single,184799,Mount Lassen,winter,40.4977,-121.42
39,"Lassen Volcanic National Park, California","Feb 14,2014",5,5,4.99,California,USA,64,M,Single,377814,Mount Lassen,winter,40.4977,-121.42
40,Zion National Park,"Feb 20,2016",5,41,4.99,North Carolina,USA,50,F,Married,455531,Zion's Main Canyon,winter,37.2982,-113.03
41,Zion National Park,"Feb 10,2016",5,41,4.99,California,USA,56,F,Married,140679,Zion's Main Canyon,winter,37.2982,-113.03
42,Zion National Park,Dec 12.2017,5,12,4.99,California,USA,38,F,Single,477426,Zion's Main Canyon,winter,37.2982,-113.03
43,Zion National Park,"Feb 6,2016",5,12,4.99,Arizona,USA,38,M,Single,494663,Zion's Main Canyon,winter,37.2982,-113.03
44,Zion National Park,"Feb 10,2018",5,12,4.99,Utah,USA,95,F,Single,466331,Zion's Main Canyon,winter,37.2982,-113.03

In [6]:
# Select the first occurrence of each station id.
parks_df = parks_df.groupby("Park").first()

# Display the new DataFrame
parks_df.head()

,Date of Review,Rating,Total Number of Reviews,Aggregate,"State,USA only",Country,Age,Gender (M or F),Relationship (Couple or Single),Occupation,Top Activity,Season,Latitude,Longitude
Park,,,,,,,,,,,,,,
"Arches National Park, Utah","Dec 10,2017",2,36,4.9,Georgia,USA,11,M,Married,494776,Delicate Arch Visit,winter,38.7331,-109.59
"Bryce Canyon National Park, Utah","Dec 26,2017",5,153,4.9,New jersey,USA,30,F,Married,203736,Bryce Canyon National Park,winter,37.5930,-112.19
"Denali National Park, Alaska","Dec 31,2017",5,27,4.9,Tennesse,USA,71,M,Married,57914,Denali,winter,63.1148,-151.19
"Grand Canyon National Park, Arizona","Dec 30,2017",5,833,4.9,Texas,USA,43,M,Married,289272,Grand Canyon South Rim,winter,36.1070,-112.11
"Lassen Volcanic National Park, California","Feb 20,2017",5,5,4.9,ohio,USA,57,M,Single,469391,Mount Lassen,winter,40.4977,-121.42

### 2. Before mapping national parks, generate DataFrame with adequate information

In [7]:
# Select Start Station Name, Latitude, and Longitude as columns in DataFrame
parks_df = parks_df.loc[:, ["Rating",
                            "Latitude",
                            "Longitude"]]
parks_df

                                           Rating  Latitude  Longitude
Park
Arches National Park, Utah                      2   38.7331    -109.59
Bryce Canyon National Park, Utah                5   37.5930    -112.19
Denali National Park, Alaska                    5   63.1148    -151.19
Grand Canyon National Park, Arizona             5   36.1070    -112.11
Lassen Volcanic National Park, California       5   40.4977    -121.42
Rocky Mountain National Park, Colorado          5   40.3428    -105.68
Yellowstone National Park, Wyoming              2   44.4280    -110.59
Yosemite National Park, California              2   37.8651    -119.54
Zion National Park                              5   37.2982    -113.03

## Plotting Markers for Each National Park

In [8]:
# Generate a map from one park location
parks_map = folium.Map(location=[61.4182147,-142.6028439],
                        zoom_start=2.9,
                        width='100%')

# Display map
parks_map

In [9]:
# Extract the location, name, and rating information for each park
for index, row in parks_df.iterrows():
    rating = row['Rating']
    lat = row['Latitude']
    lon = row['Longitude']
    name = index
    
    if rating < 3:
        index = folium.Icon(color='red')
    else:
        index = folium.Icon(color='green')
        
    ##
    popup = (
        "{name}<br>"
        "Rating: {rating}<br>"
       ).format(name=str(name), rating=str(round(rating,2)))
    ##

    #popup = folium.Popup(labels[row], parse_html=True)
    folium.Marker([lat, lon], popup=popup, icon = index).add_to(parks_map)    
    
# Create the html file with the map:
parks_map.save(outfile='parks_map.html')

# Display map
parks_map

#print(name)